import { NavCategory } from "@/types/navigation";
import {
  AlertTriangle,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  ClipboardList,
  Database,
  DollarSign,
  FileCheck,
  FileWarning,
  Fuel,
  Heart,
  History,
  Key,
  Layout,
  LineChart,
  Mail,
  Map,
  MessageSquare,
  Package,
  PieChart,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Radar,
  Radio,
  Receipt,
  Route,
  Send,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Terminal,
  Ticket,
  TrendingUp,
  Truck,
  UserCheck,
  UserPlus,
  Users,
  Wind,
  Wrench
} from "lucide-react";

// In a real app, this would be fetched from an API
export async function getNavigation(): Promise<NavCategory[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return [
    {
      id: "overview",
      title: "Overview",
      items: [
        {
          id: "dashboard",
          title: "Dashboard",
          href: "/dashboard",
          icon: Layout,
          category: "overview",
        },
        {
          id: "tracking",
          title: "Aircraft Tracking",
          href: "/dashboard/tracking",
          icon: Map,
          category: "overview",
          badge: {
            count: 12,
            variant: "secondary",
          },
        },
        {
          id: "alerts",
          title: "Active Alerts",
          href: "/dashboard/alerts",
          icon: AlertTriangle,
          category: "overview",
          badge: {
            count: 3,
            variant: "destructive",
          },
        },
        {
          id: "weather",
          title: "Weather Conditions",
          href: "/dashboard/weather",
          icon: Wind,
          category: "overview",
        },
        {
          id: "radar",
          title: "Radar View",
          href: "/dashboard/radar",
          icon: Radar,
          category: "overview",
        },
      ],
    },
    {
      id: "fleet",
      title: "Fleet Management",
      items: [
        {
          id: "aircraft",
          title: "Aircraft",
          href: "/dashboard/fleet/aircraft",
          icon: Plane,
          category: "fleet",
        },
        {
          id: "maintenance",
          title: "Maintenance",
          href: "/dashboard/fleet/maintenance",
          icon: Wrench,
          category: "fleet",
          badge: {
            count: 5,
            variant: "secondary",
          },
        },
        {
          id: "fuel",
          title: "Fuel Management",
          href: "/dashboard/fleet/fuel",
          icon: Fuel,
          category: "fleet",
        },
        {
          id: "health",
          title: "Health Monitoring",
          href: "/dashboard/fleet/health",
          icon: Heart,
          category: "fleet",
        },
        {
          id: "history",
          title: "Service History",
          href: "/dashboard/fleet/history",
          icon: History,
          category: "fleet",
        },
      ],
    },
    {
      id: "operations",
      title: "Operations",
      items: [
        {
          id: "schedule",
          title: "Flight Schedule",
          href: "/dashboard/operations/schedule",
          icon: Calendar,
          category: "operations",
        },
        {
          id: "routes",
          title: "Route Planning",
          href: "/dashboard/operations/routes",
          icon: Route,
          category: "operations",
        },
        {
          id: "departures",
          title: "Departures",
          href: "/dashboard/operations/departures",
          icon: PlaneTakeoff,
          category: "operations",
          badge: {
            count: 8,
            variant: "secondary",
          },
        },
        {
          id: "arrivals",
          title: "Arrivals",
          href: "/dashboard/operations/arrivals",
          icon: PlaneLanding,
          category: "operations",
          badge: {
            count: 6,
            variant: "secondary",
          },
        },
        {
          id: "ground",
          title: "Ground Operations",
          href: "/dashboard/operations/ground",
          icon: Terminal,
          category: "operations",
        },
      ],
    },
    {
      id: "crew",
      title: "Crew Management",
      items: [
        {
          id: "pilots",
          title: "Pilots",
          href: "/dashboard/crew/pilots",
          icon: UserCheck,
          category: "crew",
        },
        {
          id: "attendants",
          title: "Flight Attendants",
          href: "/dashboard/crew/attendants",
          icon: Users,
          category: "crew",
        },
        {
          id: "scheduling",
          title: "Crew Scheduling",
          href: "/dashboard/crew/scheduling",
          icon: ClipboardList,
          category: "crew",
        },
        {
          id: "training",
          title: "Training",
          href: "/dashboard/crew/training",
          icon: Briefcase,
          category: "crew",
        },
        {
          id: "certifications",
          title: "Certifications",
          href: "/dashboard/crew/certifications",
          icon: FileCheck,
          category: "crew",
        },
      ],
    },
    {
      id: "inventory",
      title: "Inventory & Supply",
      items: [
        {
          id: "parts",
          title: "Parts Inventory",
          href: "/dashboard/inventory/parts",
          icon: Package,
          category: "inventory",
          badge: {
            count: 15,
            variant: "secondary",
          },
        },
        {
          id: "orders",
          title: "Purchase Orders",
          href: "/dashboard/inventory/orders",
          icon: ShoppingCart,
          category: "inventory",
        },
        {
          id: "suppliers",
          title: "Suppliers",
          href: "/dashboard/inventory/suppliers",
          icon: Truck,
          category: "inventory",
        },
        {
          id: "warehouse",
          title: "Warehouse",
          href: "/dashboard/inventory/warehouse",
          icon: Building2,
          category: "inventory",
        },
        {
          id: "stock",
          title: "Stock Levels",
          href: "/dashboard/inventory/stock",
          icon: Database,
          category: "inventory",
        },
      ],
    },
    {
      id: "commercial",
      title: "Commercial",
      items: [
        {
          id: "bookings",
          title: "Bookings",
          href: "/dashboard/commercial/bookings",
          icon: Ticket,
          category: "commercial",
        },
        {
          id: "revenue",
          title: "Revenue",
          href: "/dashboard/commercial/revenue",
          icon: DollarSign,
          category: "commercial",
        },
        {
          id: "marketing",
          title: "Marketing",
          href: "/dashboard/commercial/marketing",
          icon: Send,
          category: "commercial",
        },
        {
          id: "loyalty",
          title: "Loyalty Program",
          href: "/dashboard/commercial/loyalty",
          icon: Star,
          category: "commercial",
        },
        {
          id: "feedback",
          title: "Customer Feedback",
          href: "/dashboard/commercial/feedback",
          icon: MessageSquare,
          category: "commercial",
        },
      ],
    },
    {
      id: "analytics",
      title: "Analytics & Reports",
      items: [
        {
          id: "performance",
          title: "Performance",
          href: "/dashboard/analytics/performance",
          icon: LineChart,
          category: "analytics",
        },
        {
          id: "financial",
          title: "Financial Reports",
          href: "/dashboard/analytics/financial",
          icon: TrendingUp,
          category: "analytics",
        },
        {
          id: "operational",
          title: "Operational Reports",
          href: "/dashboard/analytics/operational",
          icon: PieChart,
          category: "analytics",
        },
        {
          id: "compliance",
          title: "Compliance",
          href: "/dashboard/analytics/compliance",
          icon: Shield,
          category: "analytics",
        },
        {
          id: "predictive",
          title: "Predictive Analytics",
          href: "/dashboard/analytics/predictive",
          icon: BarChart3,
          category: "analytics",
        },
      ],
    },
    {
      id: "security",
      title: "Security & Safety",
      items: [
        {
          id: "incidents",
          title: "Incident Reports",
          href: "/dashboard/security/incidents",
          icon: FileWarning,
          category: "security",
        },
        {
          id: "compliance",
          title: "Safety Compliance",
          href: "/dashboard/security/compliance",
          icon: Shield,
          category: "security",
        },
        {
          id: "training",
          title: "Safety Training",
          href: "/dashboard/security/training",
          icon: Briefcase,
          category: "security",
        },
        {
          id: "audits",
          title: "Security Audits",
          href: "/dashboard/security/audits",
          icon: ClipboardList,
          category: "security",
        },
        {
          id: "access",
          title: "Access Control",
          href: "/dashboard/security/access",
          icon: Key,
          category: "security",
        },
      ],
    },
    {
      id: "communications",
      title: "Communications",
      items: [
        {
          id: "notifications",
          title: "Notifications",
          href: "/dashboard/communications/notifications",
          icon: Bell,
          category: "communications",
          badge: {
            count: 8,
            variant: "secondary",
          },
        },
        {
          id: "messages",
          title: "Messages",
          href: "/dashboard/communications/messages",
          icon: Mail,
          category: "communications",
        },
        {
          id: "radio",
          title: "Radio Communications",
          href: "/dashboard/communications/radio",
          icon: Radio,
          category: "communications",
        },
        {
          id: "emergency",
          title: "Emergency Alerts",
          href: "/dashboard/communications/emergency",
          icon: AlertTriangle,
          category: "communications",
        },
        {
          id: "logs",
          title: "Communication Logs",
          href: "/dashboard/communications/logs",
          icon: History,
          category: "communications",
        },
      ],
    },
    {
      id: "settings",
      title: "Settings & Configuration",
      items: [
        {
          id: "general",
          title: "General Settings",
          href: "/dashboard/settings/general",
          icon: Settings,
          category: "settings",
        },
        {
          id: "users",
          title: "User Management",
          href: "/dashboard/settings/users",
          icon: UserPlus,
          category: "settings",
        },
        {
          id: "roles",
          title: "Roles & Permissions",
          href: "/dashboard/settings/roles",
          icon: Key,
          category: "settings",
        },
        {
          id: "integrations",
          title: "Integrations",
          href: "/dashboard/settings/integrations",
          icon: Server,
          category: "settings",
        },
        {
          id: "billing",
          title: "Billing & Invoices",
          href: "/dashboard/settings/billing",
          icon: Receipt,
          category: "settings",
        },
      ],
    },
  ];
} 